spring.application.name=pdfsortspring
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
directory=/home/harry/Documents/Scans/temp-dir-springpdf/temp-images
default-dpi=10

config.dpi-list=72, 100, 150, 200, 250, 300, 400